export const users = [
    
    
    
  {
    id: "1",
    name: "Israel Johnson",
    email: "israel.johnson@example.com",
    age: 25,
    location: "Lagos, Nigeria",
    role: "Frontend Developer",
    bio: "Passionate about creating beautiful web interfaces.",
    profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: "2",
    name: "Sarah Adewale",
    email: "sarah.adewale@example.com",
    age: 28,
    location: "Abuja, Nigeria",
    role: "Backend Developer",
    bio: "Loves building secure and scalable APIs.",
    profilePic: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: "3",
    name: "Daniel Obi",
    email: "daniel.obi@example.com",
    age: 22,
    location: "Port Harcourt, Nigeria",
    role: "Fullstack Developer",
    bio: "Combines frontend and backend like magic.",
    profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: "4",
    name: "Chinwe Okoro",
    email: "chinwe.okoro@example.com",
    age: 26,
    location: "Enugu, Nigeria",
    role: "UI/UX Designer",
    bio: "Designs with users at heart.",
    profilePic: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: "5",
    name: "Emeka Nnaji",
    email: "emeka.nnaji@example.com",
    age: 30,
    location: "Asaba, Nigeria",
    role: "DevOps Engineer",
    bio: "Keeps systems running smoothly.",
    profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: "6",
    name: "Adaeze Umeh",
    email: "adaeze.umeh@example.com",
    age: 23,
    location: "Owerri, Nigeria",
    role: "Mobile App Developer",
    bio: "Builds smooth experiences for mobile users.",
    profilePic: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: "7",
    name: "Tunde Balogun",
    email: "tunde.balogun@example.com",
    age: 29,
    location: "Ibadan, Nigeria",
    role: "Data Analyst",
    bio: "Turns data into insights.",
    profilePic: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: "8",
    name: "Ngozi Eze",
    email: "ngozi.eze@example.com",
    age: 24,
    location: "Benin City, Nigeria",
    role: "Product Manager",
    bio: "Bridges users and developers.",
    profilePic: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: "9",
    name: "Kelechi Okafor",
    email: "kelechi.okafor@example.com",
    age: 27,
    location: "Ilorin, Nigeria",
    role: "QA Engineer",
    bio: "Ensures everything works perfectly.",
    profilePic: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: "10",
    name: "Blessing Musa",
    email: "blessing.musa@example.com",
    age: 21,
    location: "Kaduna, Nigeria",
    role: "Tech Support",
    bio: "Helps users solve problems fast.",
    profilePic: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: "11",
    name: "Obinna Chukwu",
    email: "obinna.chukwu@example.com",
    age: 31,
    location: "Makurdi, Nigeria",
    role: "System Administrator",
    bio: "Maintains critical systems and networks.",
    profilePic: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: "12",
    name: "Grace Agbo",
    email: "grace.agbo@example.com",
    age: 26,
    location: "Jos, Nigeria",
    role: "Content Creator",
    bio: "Creates helpful tech tutorials.",
    profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: "13",
    name: "Victor Akin",
    email: "victor.akin@example.com",
    age: 24,
    location: "Abeokuta, Nigeria",
    role: "Cloud Engineer",
    bio: "Deploys apps to the cloud effortlessly.",
    profilePic: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: "14",
    name: "Ruth Oladimeji",
    email: "ruth.oladimeji@example.com",
    age: 23,
    location: "Uyo, Nigeria",
    role: "Technical Writer",
    bio: "Writes clear developer documentation.",
    profilePic: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: "15",
    name: "Michael Udo",
    email: "michael.udo@example.com",
    age: 27,
    location: "Awka, Nigeria",
    role: "Blockchain Developer",
    bio: "Builds decentralized apps.",
    profilePic: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: "16",
    name: "Faith Ogbonna",
    email: "faith.ogbonna@example.com",
    age: 22,
    location: "Calabar, Nigeria",
    role: "Cybersecurity Specialist",
    bio: "Protects systems from hackers.",
    profilePic: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: "17",
    name: "Ibrahim Sani",
    email: "ibrahim.sani@example.com",
    age: 28,
    location: "Sokoto, Nigeria",
    role: "AI Engineer",
    bio: "Creates intelligent systems.",
    profilePic: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: "18",
    name: "Peace Nwachukwu",
    email: "peace.nwachukwu@example.com",
    age: 25,
    location: "Yola, Nigeria",
    role: "Data Scientist",
    bio: "Makes sense of big data.",
    profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: "19",
    name: "Samuel Ayodele",
    email: "samuel.ayodele@example.com",
    age: 30,
    location: "Osogbo, Nigeria",
    role: "Tech Recruiter",
    bio: "Connects great talent with great companies.",
    profilePic: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: "20",
    name: "Deborah Ibe",
    email: "deborah.ibe@example.com",
    age: 22,
    location: "Lokoja, Nigeria",
    role: "Frontend Intern",
    bio: "Learning and growing every day.",
    profilePic: "https://randomuser.me/api/portraits/women/20.jpg",
  },
];

